version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: quark_production_django
    depends_on:
      - postgres
      - redis
    expose:
      - "5000"
    volumes:
      - /opt/media:/app/apps/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    environment:  
      - VIRTUAL_HOST=quidditch.at
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=quidditch.at
      - LETSENCRYPT_EMAIL=juergen.brandl@gmail.com
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: quark_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: quark_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: quark_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: quark_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
    
networks:
  default:
    external:
      name: nginx-proxy
