# Generated by Django 2.2.2 on 2020-02-23 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
