# Generated by Django 2.2.2 on 2020-03-01 22:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Assistent Ref'), ('S', 'Snitch Ref'), ('H', 'Head Ref')], default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='positions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Chaser'), ('K', 'Keeper'), ('B', 'Beater'), ('S', 'Seeker')], default=None, max_length=7),
            preserve_default=False,
        ),
    ]
