# Generated by Django 2.2.2 on 2020-03-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200301_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
