# Generated by Django 2.2.2 on 2020-03-02 00:29

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizenship',
            field=django_countries.fields.CountryField(default="NZ", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, upload_to='You/media/uploads'),
        ),
    ]
