# Generated by Django 2.2.2 on 2020-03-02 18:35

from django.db import migrations, models
import imagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagefield.fields.ImageField(blank=True, height_field='avatar_height', upload_to='avatars', verbose_name='avatar', width_field='avatar_width'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_ppoi',
            field=imagefield.fields.PPOIField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
