from django.db import models


NGB_CHOICES =(
    ("AQArg","Argentina"),
    ("QA","Australia"),
    ("QAT","Austria"),
    ("BQF","Belgium"),
    ("ABRQ","Brasil"),
    ("QC","Canada"),
    ("AQC","Catalonia"),
    ("ACQ","Chile"),
    ("CAF","Czech Republic"),
    ("DQF","Denmark"),
    ("QF","Finland"),
    ("FQF","France"),
    ("DQB","Germany"),
    ("HKQA","Hong Kong"),
    ("QSÍ","Iceland"),
    ("QI","India"),
    ("QIRE","Ireland"),
    ("AIQ","Italy"),
    ("JQA","Japan"),
    ("QM","Malaysia"),
    ("QMX","México"),
    ("QNL","Netherlands"),
    ("QNZ","New Zealand"),
    ("NRF","Norway"),
    ("FDPQ","Peru"),
    ("PLQ","Poland"),
    ("QPt","Portugal"),
    ("QK","Korea"),
    ("QS","Serbia"),
    ("SQA","Slovakia"),
    ("QSVN","Slovenia"),
    ("AQE","Spain"),
    ("SvQF","Sweden"),
    ("SQV","Switzerland"),
    ("QD","Turkey"),
    ("QU","Uganda"),
    ("QUK","UK"),
    ("VQA","Vietnam"),
    ("Other","Not listed"),
)
